// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnd11SuNOd3KdiOePowSS_21Y_YYU6Kzs',
    appId: '1:991022682304:android:766c35f29731a6c90c5d25',
    messagingSenderId: '991022682304',
    projectId: 'foodiehub-d8dce',
    databaseURL: 'https://foodiehub-d8dce-default-rtdb.firebaseio.com',
    storageBucket: 'foodiehub-d8dce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAgYOFVCwkY9LWWJtXDwo5ivNiYqwXIkw',
    appId: '1:991022682304:ios:8337c396269eb2dd0c5d25',
    messagingSenderId: '991022682304',
    projectId: 'foodiehub-d8dce',
    databaseURL: 'https://foodiehub-d8dce-default-rtdb.firebaseio.com',
    storageBucket: 'foodiehub-d8dce.appspot.com',
    iosBundleId: 'com.example.foodieHub',
  );
}
